### ISSUE TITLE
errors on getting data for graphs

### ISSUE THREAD

**Issue by Lelant** [Lelant/director-musices-new-version#16]
sometimes the values coming back from get_attribute and similar functions are None, catch to prevent errors.

**Comment by Lelant** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in _call_
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/Users/andreasbach/Daten ab ca. 2012/Geschäftliches/Programmieren in Python lernen, Python-Programme,  12.8.23/Masterarbeit-app-main, Version 30.11.23, 8.12.23/main.py", line 153, in applyRules
    rule.apply()
  File "/Users/andreasbach/Daten ab ca. 2012/Geschäftliches/Programmieren in Python lernen, Python-Programme,  12.8.23/Masterarbeit-app-main, Version 30.11.23, 8.12.23/rules/decrease_dur.py", line 56, in apply
    self.apply_decrease_dur()
  File "/Users/andreasbach/Daten ab ca. 2012/Geschäftliches/Programmieren in Python lernen, Python-Programme,  12.8.23/Masterarbeit-app-main, Version 30.11.23, 8.12.23/rules/decrease_dur.py", line 150, in apply_decrease_dur
    add_duration(noteRest, get_attribute(noteRest, "decrease_value_dur"), idx, notesAndRests)
  File "/Users/andreasbach/Daten ab ca. 2012/Geschäftliches/Programmieren in Python lernen, Python-Programme,  12.8.23/Masterarbeit-app-main, Version 30.11.23, 8.12.23/scoreAndPerformance.py", line 471, in add_duration
    add_attribute_using_performed_note_array(get_performed_note(currentNotesAndRestsOfSameVoice[i]), 'onset_sec', value)
  File "/Users/andreasbach/Daten ab ca. 2012/Geschäftliches/Programmieren in Python lernen, Python-Programme,  12.8.23/Masterarbeit-app-main, Version 30.11.23, 8.12.23/scoreAndPerformance.py", line 631, in add_attribute_using_performed_note_array
    if _performedNote['id'] == note['id']:
       ~~~~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Lelant** [comment]
solved with #29
